# Generated by Django 4.1.7 on 2023-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
    ]
