# Generated by Django 4.1.7 on 2023-02-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Дата на създаване')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Последна модификация')),
                ('title', models.CharField(max_length=30, verbose_name='Име')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
