# Generated by Django 4.1.7 on 2023-02-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_create_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Име')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('multiple_amount', models.PositiveIntegerField(verbose_name='Кратно количество')),
            ],
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'Град', 'verbose_name_plural': 'Градове'},
        ),
    ]
