# Generated by Django 4.1.7 on 2023-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_product_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
